---
title: "Weather Station Summary"
output: html_document
---

<!-- Eduardo Klein -->
<!-- eklein at ocean-anaylitcs dot com dot au -->
<!-- 2021-05-20 -->


```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F}
# make this an external chunk that can be included in any file
require(knitr)
options(width = 100)
opts_chunk$set(echo =F, message = F, error = F, warning = F, comment = NA,  
               fig.align = 'left',  fig.width = 7.5, fig.height = 6,
               tidy = F, cache.path = '.cache/', fig.path = 'fig/')
               
library(RColorBrewer)
palette(brewer.pal(8, "Set2"))

library(leaflet)
library(jsonlite)
library(sparkline)
library(kableExtra)
library(formattable)
library(dplyr)

# Suppress summarise info
options(dplyr.summarise.inform = FALSE)
```

last run `r Sys.time()`



```{r}

makeWStable = function(site){
  ws = fromJSON(paste0("https://api.aims.gov.au/weather/station/", site))
  paramList = names(ws$series)
  param = paramList[1]
  online = formatter("span",
    style = x ~ style(color = ifelse(x, "green", "red")),
    x ~ icontext(ifelse(x, "ok", "remove"), ifelse(x, "Yes", "No")))
  
  dfAll = data.frame(Parameter = ws$series[[param]]$parameterName,
                  seriesID = ws$series[[param]]$series_id,
                  units = ws$series[[param]]$uomSymbol,
                  QAQC = paste0(unique(ws$series[[param]]$data7Days$flag), collapse = ", "),
                  online = online(as.logical(ws$series[[param]]$status$online)),
                  lastReading = ws$series[[param]]$minutesAgo,
                  lastValue = tail(as.numeric(ws$series[[param]]$data7Days$qc), 1),
                  max7Days = max(as.numeric(ws$series[[param]]$data7Days$qc)),
                  min7Days = min(as.numeric(ws$series[[param]]$data7Days$qc)),
                  Last12Hours = spk_chr(as.numeric(ws$series[[param]]$data12Hours$qc)),
                  Last7D = spk_chr(as.numeric(ws$series[[param]]$data7Days$qc)))
  
  
  for (param in paramList[-1]){
    df = data.frame(Parameter = ws$series[[param]]$parameterName,
                    seriesID = ws$series[[param]]$series_id,
                    units = ws$series[[param]]$uomSymbol,
                    QAQC = paste0(unique(ws$series[[param]]$data12Hours$flag), collapse = ", "),
                    online = online(as.logical(ws$series[[param]]$status$online)),
                    lastReading = ws$series[[param]]$minutesAgo,
                    lastValue = tail(as.numeric(ws$series[[param]]$data7Days$qc), 1),
                    max7Days = max(as.numeric(ws$series[[param]]$data7Days$qc)),
                    min7Days = min(as.numeric(ws$series[[param]]$data7Days$qc)),
                    Last12Hours = spk_chr(as.numeric(ws$series[[param]]$data12Hours$qc)),
                    Last7D = spk_chr(as.numeric(ws$series[[param]]$data7Days$qc)))
    dfAll = bind_rows(dfAll, df)
  }
 
  return(list(site=paste0(ws$site_id, " - ", ws$site_name), table=dfAll))
}

```

```{r results='asis'}
## select one of the station ID
# +-------------------------+------------+-----------------------------------------------------------------------------+
# |       Station Name      | Station ID |                                 Metadata url                                |
# +-------------------------+------------+-----------------------------------------------------------------------------+
# | Agincourt Reef Number 3 |     1      | https://apps.aims.gov.au/metadata/view/5ee39300-4ade-11dc-8f56-00008a07204e |
# |    Cape Bowling Green   |     2      | https://apps.aims.gov.au/metadata/view/5f30a190-4ade-11dc-8f56-00008a07204e |
# |      Cleveland Bay      |     3      | https://apps.aims.gov.au/metadata/view/82422310-5a9d-11dc-8d3c-00008a07204e |
# |          Darwin         |    1092    | https://apps.aims.gov.au/metadata/view/9c7a97f2-a06a-446c-9712-c6e719da0d24 |
# |       Davies Reef       |     4      | https://apps.aims.gov.au/metadata/view/5fc91100-4ade-11dc-8f56-00008a07204e |
# |        Hardy Reef       |     6      | https://apps.aims.gov.au/metadata/view/603df2e0-4ade-11dc-8f56-00008a07204e |
# |       Heron Island      |    130     | https://apps.aims.gov.au/metadata/view/aefce70d-0ca2-494a-a8f9-47499e2c7f6e |
# |      Lizard Island      |    1166    | https://apps.aims.gov.au/metadata/view/efc69c33-528f-4853-99aa-74d73e0daffa |
# |       Masig Island      |    2601    | https://apps.aims.gov.au/metadata/view/5e211d53-549b-4162-b67c-9c05c1897a7b |
# |      Myrmidon Reef      |     7      | https://apps.aims.gov.au/metadata/view/60b0d8f0-4ade-11dc-8f56-00008a07204e |
# |      Ningaloo Reef      |     8      | https://apps.aims.gov.au/metadata/view/06ea6230-55f3-11dc-8d3c-00008a07204e |
# |     One Tree Island     |    131     | https://apps.aims.gov.au/metadata/view/ee22a601-97cf-4b91-ac85-36c0198f912c |
# |       Square Rocks      |     5      | https://apps.aims.gov.au/metadata/view/1b1c2a50-4f9e-11dc-9c63-00008a07204e |
# |     Thursday Island     |    921     | https://apps.aims.gov.au/metadata/view/911a0982-240e-4461-ac0c-107f6e59a355 |
# |         Yongala         |    1165    | https://apps.aims.gov.au/metadata/view/88ef50ff-262e-49b5-90a1-70c3a570045d |
# +-------------------------+------------+-----------------------------------------------------------------------------+

sparkline(0)
site = 1166
wstable = makeWStable(site)

formattable(wstable$table, caption=wstable$site, 
            col.names=c("Parameter", "Series ID", "units", "QC flags", "is online?", "last read (minutes)", "last Value", 
                        "7days max", "7days min", "last 12h", "last 7d"))

```

